### ISSUE TITLE
Need to reload config after changes in the config file (napalm.yaml)

### ISSUE THREAD

**Issue by mab27** [StackStorm-Exchange/stackstorm-napalm#18]
Suggest adding this to the configuration section in the README:

For every change in the config file (/opt/stackstorm/configs/napalm.yaml)
You need reload the config for the changes to take effect: `st2ctl reload --register-configs`.

**Comment by Mierdin** [comment]
This is well documented at https://docs.stackstorm.com/reference/pack_configs.html

**Comment by mab27** [comment]
Indeed, absolutly right. Have'nt realized it is the normal behaviour. Issue should be closed.
