### ISSUE TITLE
napalm.get_bgp_neighbors_detail exits with error

### ISSUE THREAD

**Issue by hz2102** [StackStorm-Exchange/stackstorm-napalm#24]
Hi all,

napalm.get_bgp_neighbors_detail doesn't working.
Below is the output.

> root@bwc:~# st2 run napalm.get_bgp_neighbors_detail hostname=vmx01 neighbor=1.0.0.2  
..
id: 595c40897c1d9669e02fe289
status: failed
parameters: 
  hostname: vmx01
  neighbor: 1.0.0.2
result: 
  exit_code: 0
  result: 'unsupported operand type(s) for +=: ''int'' and ''NoneType'''
  stderr: 'st2.actions.python.NapalmGetBGPNeighborDetail: ERROR    unsupported operand type(s) for +=: ''int'' and ''NoneType''
    '
  stdout: ''

I have checked issue #14 and #15 and also checked the related .py files,
seems ok to me.

Also  napalm.get_bgp_neighbors exits with error too.

> root@bwc:~# st2 run napalm.get_bgp_neighbors hostname=vmx01                                                     
..
id: 595c438a7c1d9669e02fe28c
status: failed
parameters: 
  hostname: vmx01
result: 
  exit_code: 0
  result: list index out of range
  stderr: 'st2.actions.python.NapalmGetBGPneighbors: ERROR    list index out of range
    '
  stdout: ''

All the other commands seems like working without error.

Regards,
hz2102

**Comment by hz2102** [comment]
Update @ 6th July 2017.
Earlier logs are all from Ubuntu16.04
So I also tried with Ubuntu14.04 and the result was same.

> root@st2:/opt/stackstorm/packs/napalm# st2 run napalm.get_bgp_neighbors_detail hostname=vmx01 neighbor=1.0.0.2
..
id: 595dd489bda1902ce311b5f9
status: failed
parameters: 
  hostname: vmx01
  neighbor: 1.0.0.2
result: 
  exit_code: 0
  result: 'unsupported operand type(s) for +=: ''int'' and ''NoneType'''
  stderr: 'st2.actions.python.NapalmGetBGPNeighborDetail: ERROR    unsupported operand type(s) for +=: ''int'' and ''NoneType''
    '
  stdout: ''

By the way, following command executed without error on both Ubuntu versions.

> root@st2:/opt/stackstorm/packs/napalm# st2 run napalm.get_facts hostname=vmx01
....
id: 595dd4a4bda1902ce311b5fc
status: succeeded
parameters: 
  hostname: vmx01
result: 
  exit_code: 0
  result:
    raw:
      fqdn: MX1
      hostname: MX1
      interface_list:
      - ge-0/0/0
 'snip'

I am not so much familiar with stackstorm and napalm, just started trying this two from this week.
So any comments to narrow the problem down is also helpful.

Regards,
Hadi

**Comment by LindsayHill** [comment]
What sort of devices are you testing against? What configuration do they have? What BGP neighbors do they show if you run `sh ip bgp sum`, or the equivalent?

**Comment by hz2102** [comment]
Hi, 

I am testing against a vMX (Junos device). 
Configuration is normal MPLS configuration with 2 iBGP neighbors, exchanging EVPN routes.

> user@MX1-NTI-OC-NA> show bgp summary 
Groups: 1 Peers: 2 Down peers: 0
Table          Tot Paths  Act Paths Suppressed    History Damp State    Pending
bgp.l3vpn.0          
                       4          4          0          0          0          0
bgp.l2vpn.0          
                       2          2          0          0          0          0
Peer                     AS      InPkt     OutPkt    OutQ   Flaps Last Up/Dwn State|#Active/Received/Accepted/Damped...
1.0.0.2               65500     158122     158107       0       9 7w0d 12:19:16 Establ
`<snip>`
1.0.0.3               65500      81661      81669       0       1 3w4d 14:49:51 Establ
`<snip>`

I have also checked with https://github.com/napalm-automation/napalm-junos/issues. 
Seems like this one is reported as bug there.
![image](https://user-images.githubusercontent.com/24771255/28095590-26305b8e-66de-11e7-8396-ee5b0654a53a.png)

**Comment by LindsayHill** [comment]
Thanks for the further details. Looks like you're right, and it's a problem with upstream. Hopefully they can resolve it soon. Once it's fixed upstream, you'll be able to update your pack's virtualenv, and things should start working.

**Comment by hz2102** [comment]
ok :)
So I am closing this one.
