### ISSUE TITLE
Driver Reunification

### ISSUE THREAD

**Issue by Mierdin** [StackStorm-Exchange/stackstorm-napalm#26]
NAPALM will be unifying drivers under one repo in the near-future. Need to ensure we're prepared for it (at least pin deps versions for now)

https://napalm-automation.net/reunification/

**Comment by LindsayHill** [comment]
Related issue here: this pack won't work with pip >= 10.0

napalm-base uses `from pip.req import parse_requirements`, which won't work anymore.

napalm-base is no longer maintained, after the drivers were reunified into napalm. 

ST2 uses pip 9.x, but at some point this will get updated to use current pip versions. We need to update this pack to ensure it works with the new unified model, and new versions of pip.

**Comment by LindsayHill** [comment]
ST2 has now been updated to pip 19.x https://github.com/StackStorm/st2/issues/4681

This will ship with ST2 3.1, making this issue now critical for this pack.
