### ISSUE TITLE
ghost2logger not installing

### ISSUE THREAD

**Issue by chella2830** [StackStorm-Exchange/stackstorm-napalm#40]
Hello I am getting a error message when installing ghost2logger with error message Error index not available .Please help. When i install ghost2logger via webUI i get time out error message.

**Comment by nmaludy** [comment]
@chella2830 sounds like you might be installing this on a system without access to the internet, or maybe via a proxy?

**Comment by chella2830** [comment]
That could be it. However what is funny is that i did that for other packages like NAPLAM and NAPALM logs and it worked properly. Anyways if i need to go via proxy what do i need to do. Should i try something like this - for UBUNTU
http_proxy=http://10.1.3.1:8080  in /etc/environment

**Comment by LindsayHill** [comment]
See this page for proxy configuration https://docs.stackstorm.com/packs.html#advanced-topics
