### ISSUE TITLE
NAPALM execution

### ISSUE THREAD

**Issue by chella2830** [StackStorm-Exchange/stackstorm-napalm#41]
Hi,
1. Issue on documentation -
At this location - https://napalm.readthedocs.io/en/latest/support/nxos.html -
Prerequisites
Your device must be running NXOS 6.1. 
However at this location  - https://napalm.readthedocs.io/en/latest/support/index.html
I see the statement Minimum requirement = 6.1
So i am running NX OS  version 7.0(3)I4(3) - Will NAPALM work.
2. When i am running NAPALM via stackstorm and providing the driver as NXOS, the device running 7.0 with all the reprequistes done like enabling feature sets etc, i am getting this error message-
Exception: Configuration Error: Please provide a pack config and ensure it's loaded  with `st2ctl reload --register-configs`

So in which version does NAPALM work?

**Comment by Mierdin** [comment]
@chella2830 Regarding your first point, I'm a little confused. Both locations say you need to run 6.1 at a minimum, and you've stated you're running 7.0. So there shouldn't be a problem. Am I missing something? If you have version questions, you may want to consider raising with the NAPALM folks, this repo houses only the StackStorm pack for using the NAPALM library.

Regarding point number 2, that error message means you haven't configured the NAPALM pack. StackStorm needs to know where your switches are and how to authenticate to them. Please follow the [README](https://github.com/StackStorm-Exchange/stackstorm-napalm#configuration). You can also read up on pack configuration in general [in StackStorm's documentation](https://docs.stackstorm.com/reference/pack_configs.html).
