### ISSUE TITLE
get_config fails; cannot pass "secret" parameter

### ISSUE THREAD

**Issue by alecmart96** [StackStorm-Exchange/stackstorm-napalm#47]
get_config continuously fails via web ui. Returns this error

`ValueError: Failed to enter enable mode. Please ensure you pass the 'secret' argument to ConnectHandler.`

Unable to pass "secret" parameter

**Comment by nmaludy** [comment]
@alecmart96 can you run it OK from the command line? 

```
$ st2 run napalm.get_config hostname=10.0.0.1 driver="ios" credentials=dev
.........
id: 5b44e351a814c004961c0214
status: succeeded
parameters: 
  credentials: dev
  driver: ios
  hostname: 10.0.0.1
result: 
  exit_code: 0
  result:
    raw:
      candidate: ''
      running: "Building configuration...
...
```

**Comment by alecmart96** [comment]
I receive the same error message when run through cli. 


`id: 5b44e4469f62314f9f570d1c
status: failed
parameters: 
  credentials: core
  driver: ios
  hostname: ****
result: 
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/runners/python_runner/python_runner/python_action_wrapper.py", line 320, in <module>
    obj.run()
  File "/opt/stackstorm/runners/python_runner/python_runner/python_action_wrapper.py", line 179, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/napalm/actions/get_config.py", line 8, in run
    with self.get_driver(**std_kwargs) as device:
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/napalm/base/base.py", line 46, in __enter__
    self.open()
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/napalm/ios/ios.py", line 127, in open
    self.device.enable()
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 18, in enable
    return super(CiscoBaseConnection, self).enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/netmiko/base_connection.py", line 1162, in enable
    raise ValueError(msg)
ValueError: Failed to enter enable mode. Please ensure you pass the 'secret' argument to ConnectHandler.`

**Comment by LindsayHill** [comment]
What credentials do you have configured? Have you checked those?

**Comment by alecmart96** [comment]
Username and password are in order. My napalm.yaml config is pretty similar to napalm.yaml.example. Is there a way to pass "secret" through the configured credentials, along with the username and password?

**Comment by nmaludy** [comment]
@alecmart96 can you post what your `napalm.yaml` looks like (redacting any secret information)?

Are you reading passwords from the datastore?

**Comment by alecmart96** [comment]
The passwords are configured into napalm.yaml

`html_table_class: napalm

credentials:
  core:
    username: user
    password: ****

devices:
- hostname: ****
  driver: ios
  credentials: core
- hostname: ****
  driver: ios
  credentials: core`

**Comment by nmaludy** [comment]
@alecmart96 If you login to the switch as that user, can you run `enable` and get the elevated prompt?

**Comment by alecmart96** [comment]
Yes I can reach the enable prompt through that user

**Comment by nmaludy** [comment]
Do you have a special prompt setup on the device?

Mine looks like: 
```
Switch#
```

**Comment by alecmart96** [comment]
before and after enable mode is entered the prompt is simply

> hostname>

> hostname#

**Comment by LindsayHill** [comment]
This error is coming from netmiko, the library that Napalm uses to talk to IOS devices.

The issue is that Napalm does not have a `secret:` (aka `enable`) password parameter by default. It can be passed as an optional argument to napalm (see https://napalm.readthedocs.io/en/latest/support/index.html?#list-of-supported-optional-arguments).

Your options here are:
1/ Give that user privilege 15 by default
2/ Write an update to this pack that allows specifying a `secret` in device credentials, and passing that as an optional argument if defined

**Comment by LindsayHill** [comment]
You can test it out using this PR here #49

Install it with `st2 pack install napalm=secret`, then update your `napalm.yaml` to include a `secret` parameter. 

I have not done **any** testing with this. Try it out and see how it goes.

**Comment by alecmart96** [comment]
Passing 'secret' as an opt arg doesn't work. Still fails after execution. However, after updating the pack and adding 'secret' to napalm.yaml get_config runs and returns the config. Thank you very much for the support.

**Comment by LindsayHill** [comment]
So, just to be clear:
1/ You tested out that branch, using `st2 pack install napalm=secret`, and that worked OK?
2/ Did you test it with any devices that do *not* require the use of a secret?

I have not done **any** testing of that code, and I probably won't get the chance, so I'd like to know if it works for all users before we merge it.

**Comment by alecmart96** [comment]
To be clear, I tested `st2 pack install napalm=secret` with ios devices that required the use of a secret to enter enable mode and get_config worked successfully and returned the running configurations.
