### ISSUE TITLE
possible to add SSH keys to credentials?

### ISSUE THREAD

**Issue by devinodaniel** [StackStorm-Exchange/stackstorm-napalm#50]
In our environment, we only connect to remote hosts via SSH RSA keys. Is it possible to supply path to key instead of password?

**Comment by LindsayHill** [comment]
It's been a long time since I looked, but at the time napalm did not support SSH keys. Does it do so now? If so, then in theory it could be added here

**Comment by Mierdin** [comment]
They are supported as an [optional arg](http://napalm.readthedocs.io/en/latest/support/index.html#list-of-supported-optional-arguments). Works great, been using this since it was released. Should be able to hook through to this functionality by plumbing that optional arg through to the action code, similar to the way [@LindsayHill did recently](https://github.com/StackStorm-Exchange/stackstorm-napalm/pull/49/files#diff-26ccd7e1e73c2727ca1cd814bcb43d99R49)

**Comment by LindsayHill** [comment]
Ah, good to know. Should be _relatively_ straightforward to add then, if anyone's volunteering

**Comment by LindsayHill** [comment]
@devinodaniel I've created a work in progress PR here: https://github.com/StackStorm-Exchange/stackstorm-napalm/pull/51

Can you try installing it with `st2 pack install napalm=ssh_key`, and then add a `key_file` entry to your device credentials, reload the configuration (`sudo st2ctl reload --register-configs`), and then try an action using an SSH key?

**Comment by devinodaniel** [comment]
@LindsayHill Just got a chance to try this out. Getting the below error. I first verified that it was working with `password` and then tried with `key_file`:

`$ st2 run napalm.get_bgp_config hostname=fw01.core.lab01`

```
result: 
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/runners/python_runner/python_runner/python_action_wrapper.py", line 320, in <module>
    obj.run()
  File "/opt/stackstorm/runners/python_runner/python_runner/python_action_wrapper.py", line 179, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/napalm/actions/get_bgp_config.py", line 10, in run
    with self.get_driver(**std_kwargs) as device:
  File "/opt/stackstorm/packs/napalm/actions/lib/action.py", line 39, in get_driver
    login = self.get_credentials(found_device['credentials'])
  File "/opt/stackstorm/packs/napalm/actions/lib/action.py", line 76, in get_credentials
    if authconfig['password'] is None and authconfig['key_file'] is None:
KeyError: 'password'
"
  stdout: ''
```

**/opt/stackstorm/configs/napalm.yaml**

```
credentials:
  withkey:
    username: devin
    key_file: /home/vagrant/.ssh/napalm_test_key
  withpass:
    username: devin
    password: xxxxxxxxxx

devices:
- hostname: fw01.core.lab01
  port: 22
  driver: junos
  credentials: withkey
```

**Comment by LindsayHill** [comment]
Ah yeah, those are not defaulted to None, instead the key doesn't exist. You could try these changes https://github.com/StackStorm-Exchange/stackstorm-napalm/pull/51/commits/1c6ded402c45b05e5b3603fb8d192fb0149abc69

The only bit I'm not sure about is the setting for `password:`. That PR is now setting `password:` to `None` if key_file is set. It may actually need to be set to `''`. Can you try that out?
