### ISSUE TITLE
Disable ssl verification Arista

### ISSUE THREAD

**Issue by ognjen011** [StackStorm-Exchange/stackstorm-napalm#63]
Ok just a question. When i try to connect to my Arista switch i get the error below. This is probably because i am using a self signed cert. Is there an option to disable ssl verification?
 
napalm.base.exceptions.ConnectionException: Socket error during eAPI connection: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:852)

**Comment by LindsayHill** [comment]
Does Napalm offer a method to disable validation for EOS? [Their docs](https://napalm.readthedocs.io/en/latest/support/#the-transport-argument) indicate that this is only an option for NXOS, but I haven't looked at the code.
