### ISSUE TITLE
Can't get a action running.  stderr: 'st2.actions.python.NapalmCLI: ERROR  

### ISSUE THREAD

**Issue by mab27** [StackStorm-Exchange/stackstorm-napalm#7]
[napalm_yaml.txt](https://github.com/StackStorm-Exchange/stackstorm-napalm/files/838938/napalm_yaml.txt)

Tested the napalm pack, on JunOS device.
I configured the /opt/stackstorm/configs/napalm.yaml
but actions aren't exectued, I'm getting this:

mab@mab-infra:/opt/stackstorm/configs$ ping vmx1
PING vmx1 (192.168.0.30) 56(84) bytes of data.
64 bytes from vmx1 (192.168.0.30): icmp_seq=1 ttl=64 time=0.788 ms
64 bytes from vmx1 (192.168.0.30): icmp_seq=2 ttl=64 time=0.776 ms
^C
--- vmx1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.776/0.782/0.788/0.006 ms
mab@mab-infra:/opt/stackstorm/configs$
mab@mab-infra:/opt/stackstorm/configs$ st2 run napalm.cli hostname=vmx1 commands="show interfaces terse"
.
id: 58c691877cae2208c46ef843
status: failed
parameters:
 commands:
 - show interfaces terse
 hostname: vmx1
result:
 exit_code: 0
 result: '''devices'''
 stderr: 'st2.actions.python.NapalmCLI: ERROR    ''devices''

   '
 stdout: ''
mab@mab-infra:/opt/stackstorm/configs

**Comment by Mierdin** [comment]
@mab27 This should be fixed now that #8 is merged. Thanks for reporting!
