### ISSUE TITLE
StackStorm / Napalm merge configuration errors on \n in config_text 

### ISSUE THREAD

**Issue by rickogg** [StackStorm-Exchange/stackstorm-napalm#73]
Reviewing the example documented for NAPALM at this [link](https://napalm.readthedocs.io/en/stable/tutorials/changing_the_config.html#merging-configuration).

Multiple commands are being passed with a **\n** after each line of configuration.
device.load_merge_candidate(config='**hostname test\ninterface Ethernet2\ndescription bla**')

When attempting to do the same from within the Stackstorm action, Stackstorm is throwing errors attempting to escape the backslash characters in the text string.

**Comment by rickogg** [comment]
I was able to resolve the issue by formatting the CLI as below instead of the example shown in the napalm documentation.

st2 run napalm.loadconfig hostname=1.2.3.4 credentials=st2 driver=eos port=8443 method=merge config_text="
interface vlan 123
description abcd
"

I believe the YQML definition will look like the example in the documentation

action: napalm.loadconfig
    input:
      method: merge
      log_level: DEBUG
      hostname: 1.2.3.4
      driver: eos
      port: '8443'
      credentials: st2
      config_text: "interface vlan 123\ndescription abcd"

**Comment by floatingstatic** [comment]
Hi @rickogg thanks for the report. You beat me to the punch... I was about to mention the same as at least a workaround either in the web ui, curling the st2 api or via the st2 client. If you feel we need to support this as per the NAPALM documented example I can dig into this some more. I will note however that it seems that passing newlines appears to be NAPALM driver dependent. For example bypassing st2 completely and running `load_merge_candidate()` from a python interpreter against a device in my lab running JUNOS if i pass any `\n` characters I could not merge a config snippet with explicit newlines without getting an error.
